### ISSUE TITLE
rb-readline (0.5.3) crashes on mac_os_x / 2.3.1p112

### ISSUE THREAD

**Issue by kplimack** [ConnorAtherton/rb-readline#137]
This is reopening https://github.com/ConnorAtherton/rb-readline/issues/120, which was never fully fixed.

```
MacBook-Pro-2:knife-derp jplimack$ bundle gem knife-derp
Creating gem 'knife-derp'...
Do you want to include a code of conduct in gems you generate?
C--- ERROR REPORT TEMPLATE -------------------------------------------------------efer collaborative, safe spaces. You can read more ab- What did you do?nduct at contributor-covenant.org. Having a code of conduct means agreeing to the responsibility of enforcing it, so b
  I ran the command `/opt/chefdk/embedded/bin/bundle gem knife-derp`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...


Error details

    TypeError: no implicit conversion from nil to integer
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/rb-readline-0.5.3/lib/rbreadline.rb:2742:in `[]'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/rb-readline-0.5.3/lib/rbreadline.rb:2742:in `update_line'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/rb-readline-0.5.3/lib/rbreadline.rb:3542:in `rl_redisplay'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/rb-readline-0.5.3/lib/rbreadline.rb:3960:in `readline_internal_setup'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/rb-readline-0.5.3/lib/rbreadline.rb:4807:in `readline_internal'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/rb-readline-0.5.3/lib/rbreadline.rb:4830:in `readline'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/rb-readline-0.5.3/lib/readline.rb:45:in `readline'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/line_editor/readline.rb:20:in `readline'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/line_editor.rb:7:in `readline'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/shell/basic.rb:395:in `ask_simply'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/shell/basic.rb:68:in `ask'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/shell/basic.rb:111:in `yes?'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/ui/shell.rb:56:in `yes?'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/gem.rb:155:in `ask_and_set'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/gem.rb:100:in `run'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:384:in `gem'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
      /opt/chefdk/embedded/bin/bundle:22:in `load'
      /opt/chefdk/embedded/bin/bundle:22:in `<main>'

Environment

  Bundler   1.12.5
  Rubygems  2.6.10
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin13]
  GEM_HOME  /Users/jplimack/.chefdk/gem/ruby/2.3.0
  GEM_PATH  /Users/jplimack/.chefdk/gem/ruby/2.3.0:/opt/chefdk/embedded/lib/ruby/gems/2.3.0
  Git       2.10.1 (Apple Git-78)

      Bundler settings

  gem.test
    Set for your local app (/Users/jplimack/.bundle/config): "rspec"
    Set for the current user (/Users/jplimack/.bundle/config): "rspec"
  gem.mit
    Set for your local app (/Users/jplimack/.bundle/config): "false"
    Set for the current user (/Users/jplimack/.bundle/config): "false"
  orig_path
    Set via BUNDLE_ORIG_PATH: "/opt/chefdk/bin:/Users/jplimack/.chefdk/gem/ruby/2.3.0/bin:/opt/chefdk/embedded/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/sbin:/usr/local/go/bin:/Users/jplimack/go/bin:/opt/chefdk/gitbin"
  orig_gem_path
    Set via BUNDLE_ORIG_GEM_PATH: "/Users/jplimack/.chefdk/gem/ruby/2.3.0:/opt/chefdk/embedded/lib/ruby/gems/2.3.0"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=no+implicit+conversion+from+nil+to+integer&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new
MacBook-Pro-2:knife-derp jplimack$ gem list | grep readline
rb-readline (0.5.3)
```

**Comment by kplimack** [comment]
this fixed it
```
MacBook-Pro-2:knife-derp jplimack$ gem update thor rb-readline
Updating installed gems
Updating rb-readline
Fetching: rb-readline-0.5.4.gem (100%)
Successfully installed rb-readline-0.5.4
Gems updated: rb-readline
Gems already up-to-date: thor
```
