### ISSUE TITLE
Invalid byte sequence in UTF-8 when running console

### ISSUE THREAD

**Issue by johnnyshields** [ConnorAtherton/rb-readline#139]
On Windows 10, Ruby 2.4.1

Issue happens on 0.4.0+ and master

Tried `require: false`, doesn't fix the issue.

Very strange because it seems like this was working at one point.

```
Loading development environment (Rails 5.1.2)
C:/ruby24/lib/ruby/gems/2.4.0/bundler/gems/rb-readline-fd882edcd145/lib/rbreadline.rb:6135:in `delete': invalid byte sequence in UTF-8 (ArgumentError)
        from C:/ruby24/lib/ruby/gems/2.4.0/bundler/gems/rb-readline-fd882edcd145/lib/rbreadline.rb:6135:in `alloc_history_entry'
        from C:/ruby24/lib/ruby/gems/2.4.0/bundler/gems/rb-readline-fd882edcd145/lib/rbreadline.rb:6168:in `add_history'
        from C:/ruby24/lib/ruby/gems/2.4.0/bundler/gems/rb-readline-fd882edcd145/lib/readline.rb:368:in `<<'
        from C:/ruby24/lib/ruby/2.4.0/irb/ext/save-history.rb:76:in `block (2 levels) in load_history'
        from C:/ruby24/lib/ruby/2.4.0/irb/ext/save-history.rb:76:in `each'
        from C:/ruby24/lib/ruby/2.4.0/irb/ext/save-history.rb:76:in `block in load_history'
        from C:/ruby24/lib/ruby/2.4.0/open-uri.rb:37:in `open'
        from C:/ruby24/lib/ruby/2.4.0/open-uri.rb:37:in `open'
        from C:/ruby24/lib/ruby/2.4.0/irb/ext/save-history.rb:75:in `load_history'
        from C:/ruby24/lib/ruby/2.4.0/irb/ext/save-history.rb:65:in `extended'
        from C:/ruby24/lib/ruby/2.4.0/irb/ext/save-history.rb:21:in `extend'
        from C:/ruby24/lib/ruby/2.4.0/irb/ext/save-history.rb:21:in `init_save_history'
        from C:/ruby24/lib/ruby/2.4.0/irb/ext/save-history.rb:45:in `save_history='
        from C:/ruby24/lib/ruby/2.4.0/irb/context.rb:92:in `initialize'
        from C:/ruby24/lib/ruby/2.4.0/irb.rb:412:in `new'
        from C:/ruby24/lib/ruby/2.4.0/irb.rb:412:in `initialize'
        from C:/ruby24/lib/ruby/2.4.0/irb.rb:383:in `new'
        from C:/ruby24/lib/ruby/2.4.0/irb.rb:383:in `start'
        from C:/ruby24/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/commands/console/console_command.rb:62:in `start'
        from C:/ruby24/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/commands/console/console_command.rb:17:in `start'
        from C:/ruby24/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/commands/console/console_command.rb:85:in `perform'
        from C:/ruby24/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from C:/ruby24/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/ruby24/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from C:/ruby24/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/command/base.rb:63:in `perform'
        from C:/ruby24/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/command.rb:44:in `invoke'
        from C:/ruby24/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by johnnyshields** [comment]
OK I figured out the issue, I had pasted non-UTF-8 chars into my console, and it can't load the history. I will raise a patch for this.

**Comment by daetherius** [comment]
I had this problem in a Windows machine and solved it by emptying the `.irb_history` file at home directory (`C:\Users\<username>\` in Windows), since I couldn't locate the line with the offender character. Just another drawbacks of copy-pasting from stackoverflow 😅

**Comment by victorsabreu** [comment]
> I had this problem in a Windows machine and solved it by emptying the `.irb_history` file at home directory (`C:\Users\<username>\` in Windows), since I couldn't locate the line with the offending character.
> 
> Just another drawback of copy-pasting from stackoverflow 😅

Work for me.. Thanks man!

**Comment by yossepbb** [comment]
> I had this problem in a Windows machine and solved it by emptying the .irb_history file at home directory (C:\Users\<username>\ in Windows), since I couldn't locate the line with the offending character.

Just another drawback of copy-pasting from stackoverflow

> 

Thank you , it also works for me. Have a good time.

**Comment by lflucasferreira** [comment]
I didn't find the file .irb_history

But I fixed by removing the file **pry_history** under **/users/.local/share/pry**
