### ISSUE TITLE
rb-readline-0.5.0 with Rails 4.0.0.beta1 (Windows7)

### ISSUE THREAD

**Issue by DHB** [ConnorAtherton/rb-readline#84]
I admit #83 was maybe a bit tl;dr …

The problem however is still the same … Cannot start the console with rails c ...

``` shell
$ rails c
DL is deprecated, please use Fiddle
Loading development environment (Rails 4.0.0.beta1)
h:/ruby200_p0/lib/ruby/2.0.0/irb/input-method.rb:150:in `gets': uninitialized constant IRB::ReadlineInputMethod::Readline (NameError)
        from h:/ruby200_p0/lib/ruby/2.0.0/irb.rb:472:in `block (2 levels) in eval_input'
        from h:/ruby200_p0/lib/ruby/2.0.0/irb.rb:624:in `signal_status'
        from h:/ruby200_p0/lib/ruby/2.0.0/irb.rb:471:in `block in eval_input'
        from h:/ruby200_p0/lib/ruby/2.0.0/irb/ruby-lex.rb:190:in `call'
        from h:/ruby200_p0/lib/ruby/2.0.0/irb/ruby-lex.rb:190:in `buf_input'
        from h:/ruby200_p0/lib/ruby/2.0.0/irb/ruby-lex.rb:105:in `getc'
        from h:/ruby200_p0/lib/ruby/2.0.0/irb/slex.rb:206:in `match_io'
        from h:/ruby200_p0/lib/ruby/2.0.0/irb/slex.rb:76:in `match'
        from h:/ruby200_p0/lib/ruby/2.0.0/irb/ruby-lex.rb:290:in `token'
        from h:/ruby200_p0/lib/ruby/2.0.0/irb/ruby-lex.rb:266:in `lex'
        from h:/ruby200_p0/lib/ruby/2.0.0/irb/ruby-lex.rb:237:in `block (2 levels) in each_top_level_statement'
        from h:/ruby200_p0/lib/ruby/2.0.0/irb/ruby-lex.rb:233:in `loop'
        from h:/ruby200_p0/lib/ruby/2.0.0/irb/ruby-lex.rb:233:in `block in each_top_level_statement'
        from h:/ruby200_p0/lib/ruby/2.0.0/irb/ruby-lex.rb:232:in `catch'
        from h:/ruby200_p0/lib/ruby/2.0.0/irb/ruby-lex.rb:232:in `each_top_level_statement'
        from h:/ruby200_p0/lib/ruby/2.0.0/irb.rb:488:in `eval_input'
        from h:/ruby200_p0/lib/ruby/2.0.0/irb.rb:397:in `block in start'
        from h:/ruby200_p0/lib/ruby/2.0.0/irb.rb:396:in `catch'
        from h:/ruby200_p0/lib/ruby/2.0.0/irb.rb:396:in `start'
        from h:/ruby200_p0/lib/ruby/gems/2.0.0/gems/railties-4.0.0.beta1/lib/rails/commands/console.rb:88:in `start'
        from h:/ruby200_p0/lib/ruby/gems/2.0.0/gems/railties-4.0.0.beta1/lib/rails/commands/console.rb:9:in `start'
        from h:/ruby200_p0/lib/ruby/gems/2.0.0/gems/railties-4.0.0.beta1/lib/rails/commands.rb:64:in `<top (required)>'
        from bin/rails:4:in `require'
```

**Comment by shrikant1712** [comment]
I am getting same issue on Windows machine. I have rails 5 and ruby 2.3.3 installed on my machine. Can any let me know what should I do?
